name: Create terraform plan

on: [pull_request]

permissions:
  contents: write
  pull-requests: write
  id-token: write
  security-events: write

env:
  BUCKET_NAME : "terraform-state.359300022316"
  AWS_REGION : "us-west-2"

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for an example terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.org_admin_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::359300022316:role/github-configuration-ci-cd
          role-session-name: github-configuration-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: .